DROP TRIGGER IF EXISTS trg_p2p_insert_audit ON P2P;
DROP PROCEDURE IF EXISTS export;
DROP PROCEDURE IF EXISTS import;
DROP PROCEDURE IF EXISTS add_p2p_review;
DROP PROCEDURE IF EXISTS add_verter_review;
DROP TABLE IF EXISTS checks CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS p2p CASCADE;
DROP TABLE IF EXISTS peers CASCADE;
DROP TABLE IF EXISTS recommendations CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS timetracking CASCADE;
DROP TABLE IF EXISTS transferredpoints CASCADE;
DROP TABLE IF EXISTS verter CASCADE;
DROP TABLE IF EXISTS xp CASCADE;
DROP FUNCTION IF EXISTS get_all_pairs_of_peers;
DROP FUNCTION IF EXISTS fnc_trg_p2p_insert_audit;
DROP FUNCTION IF EXISTS fnc_trg_xp_insert_audit;
drop function if exists changing_points_according_to_function3;
drop function if exists changing_points_according_to_transferedpoints;
drop function if exists show_the_number_of_xp;
drop function if exists successful_and_unsuccessful_checks;
drop function if exists transferedpoints_in_human_readable_form;
DROP FUNCTION IF EXISTS get_peers_friends;
DROP FUNCTION IF EXISTS get_peers_recommended_peers;
DROP FUNCTION IF EXISTS peersfriends;
DROP TYPE IF EXISTS checkstatus;
